[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "self_encryption"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Operating System :: OS Independent",
]

[tool.maturin]
features = ["python"]
module-name = "_self_encryption"
bindings = "pyo3"
include = ["Cargo.toml", "Cargo.lock", "src/**/*", "README.md", "LICENSE"]
python-packages = ["self_encryption"]
wheel-include = ["LICENSE"]
